### ISSUE TITLE
[IMPROVEMENT] : update font family

### ISSUE THREAD

**Issue by Darrkzero** [PritamSarbajna/tourism-website#10]
I tried to analyze your website and noticed your font is kind of basic it will be nice to change the font-family, font-size and font-weight to something professional

**Comment by PritamSarbajna** [comment]
Yeah @Darrkzero I thought of that make a PR after changing the font just don't use any overwhelming font.

**Comment by PritamSarbajna** [comment]
There is already a issue about that #7
