### ISSUE TITLE
[BUG] : Bug in NavBar

### ISSUE THREAD

**Issue by subhranil002** [PritamSarbajna/tourism-website#109]
# Describe the bug
### When the user is scrolling the page the navbar is not getting updated to the others like tours, explore, about  ...
# Screenshots
### Here the user is in the contact us section but the navbar denotes it as Home
![Screenshot 2023-09-15 175230](https://github.com/PritamSarbajna/tourism-website/assets/106914208/8d1bb0f3-3eeb-43e2-b230-f3dbea13bcc3)
## Please assign me the task to fix the bug !!! ... Or you can say a new FEATURE

**Comment by PritamSarbajna** [comment]
Yeah @subhranil002, Love to see you noticed that. Work on it 🚀

**Comment by subhranil002** [comment]
Thanks for the approval ... work already started!

**Comment by subhranil002** [comment]
@PritamSarbajna can I update text formatting ?

**Comment by PritamSarbajna** [comment]
@subhranil002 Change the formatting and when submitting a PR please include in the points that what have you changed. I will merge it after making necessary changes if required.

**Comment by subhranil002** [comment]
Okay!

**Comment by subhranil002** [comment]
Hey! @PritamSarbajna ... I made a pull request yesterday ... still not accepted ... is there a problem ?
