### ISSUE TITLE
[ENHANCEMENT] : Implement dark theme

### ISSUE THREAD

**Issue by PritamSarbajna** [PritamSarbajna/tourism-website#11]
Make the website's theme dark as well as choose a dark background

**Comment by Iamslok** [comment]
@PritamSarbajna I would like to contribute, can you assign me?

**Comment by PritamSarbajna** [comment]
@Iamslok Here you go

**Comment by Iamslok** [comment]
@PritamSarbajna can we discuss about the dark theme

**Comment by PritamSarbajna** [comment]
Yeah come to #13

**Comment by Techkrish1** [comment]
Your Tourist Website is fantastic. can you assign me to work on the dark theme issue? I can solve this.

**Comment by Andyy-18** [comment]
Hey @PritamSarbajna I'm interested to work on this project. I'm a newbie. I want to contribute in it. Can i ?

**Comment by PritamSarbajna** [comment]
@Techkrish1 Hey this issue assigned to @Iamslok you can collaborate with him

**Comment by PritamSarbajna** [comment]
> Hey @PritamSarbajna I'm interested to work on this project. I'm a newbie. I want to contribute in it. Can i ?

Yeah sure @Andyy-18 why not see the issues if you can resolve any of them

**Comment by Techkrish1** [comment]
Can I implement your README?  Can you assign me?

**Comment by PritamSarbajna** [comment]
hey @Techkrish1 please comment under the issues you want to work on

**Comment by Iamslok** [comment]
https://user-images.githubusercontent.com/90669886/185296358-9c4a2e8f-0415-4cf4-b666-34785d6478e8.mp4

@PritamSarbajna This is the demo, let me know what you think.

**Comment by Techkrish1** [comment]
> ScreenRecorder_2022-08-18_b620aa15-4253-4383-8695-4dc679aaa0b1.mp4 
> @PritamSarbajna This is the demo, let me know what you think.

can we collaborate on this issue? Please give me permission.

**Comment by Iamslok** [comment]
@Techkrish1 ask @PritamSarbajna

**Comment by PritamSarbajna** [comment]
Hey @Techkrish1 you can collaborate by helping @Iamslok but don't make any personal PR because this issue is been assigned to @Iamslok

**Comment by PritamSarbajna** [comment]
Hey @Iamslok update your project and also if you need any help regarding this ask me in here #35
