### ISSUE TITLE
[BUG] : MENU not responsive

### ISSUE THREAD

**Issue by athar-ansari** [PritamSarbajna/tourism-website#114]
**Describe the bug**
MENU Button is not working Properly  like its suppose to 

**Screenshots**
![Screenshot 2023-11-06 124057](https://github.com/PritamSarbajna/tourism-website/assets/118714083/39c61265-565c-41d2-a684-f70b90e5c41a)

**Comment by PritamSarbajna** [comment]
@Debshibraj123 Here you go 🚀

**Comment by Domenez25** [comment]
@PritamSarbajna I guess the problem was not fixed, I am working on a fix can you please assign me to it?

**Comment by PritamSarbajna** [comment]
yeah sure @Domenez25

**Comment by Domenez-dev** [comment]
@PritamSarbajna @athar-ansari,  I have finished the work that was assigned to me and you can check on [pull #119](https://github.com/PritamSarbajna/tourism-website/pull/119)
