### ISSUE TITLE
[FEATURE] : Replacing Previous Arrow

### ISSUE THREAD

**Issue by athar-ansari** [PritamSarbajna/tourism-website#116]
**Is your feature request related to a problem? Please describe.**
- Replacing Previous Arrow and Making it Animated.

**Describe the solution you'd like**
![arrow](https://github.com/PritamSarbajna/tourism-website/assets/118714083/c532405a-5d00-4847-a10c-0ef63c54e9b0)

**Comment by PritamSarbajna** [comment]
Work on it 🚀
