### ISSUE TITLE
[IMPROVEMENT] : Center the logo

### ISSUE THREAD

**Issue by PritamSarbajna** [PritamSarbajna/tourism-website#15]
**Logo _(where ADVENTURE written)_ should be center inside the navbar vertically. it's now a slightly upper than it should be**

**Comment by PreciousOlamide** [comment]
Hello, I am interested in working on this task.

**Comment by AngeloTree** [comment]
Hey, I am interested in working on this task!

**Comment by PritamSarbajna** [comment]
Hey sure make a PR

**Comment by prakhartiwari2507** [comment]
Please check my PR, I have solved the issue.

**Comment by PritamSarbajna** [comment]
thanks @prakhartiwari2507 this is nice 🙌
