### ISSUE TITLE
[IMPROVEMENT] : Move this to footer

### ISSUE THREAD

**Issue by PritamSarbajna** [PritamSarbajna/tourism-website#16]
Hey contributors, please move this to footer also keep 3 icons which is LinkedIn, GitHub and a globe.

**This is the current snap :**

![Screenshot (198)](https://user-images.githubusercontent.com/90236635/184574726-d84610d4-8491-4ced-9e6f-77c0d52c392b.png)

**I want this as this :**

![Screenshot (199)](https://user-images.githubusercontent.com/90236635/184575133-5eea4b59-edc2-4a8a-8edf-0f880c8a88e2.png)

**Comment by JumaCodes** [comment]
I would love to work and solve this issue and make it look like this image below
![open source image1](https://user-images.githubusercontent.com/73387073/184610375-82cc4bdb-9a33-45a5-a18b-8e9327169207.png)

**Comment by PritamSarbajna** [comment]
Yeah @JumaCodes go for it man. would love to see it

**Comment by PritamSarbajna** [comment]
thanks @JumaCodes. I also think this #20 is for you.
