### ISSUE TITLE
[BUG] : In hover, covering content

### ISSUE THREAD

**Issue by PritamSarbajna** [PritamSarbajna/tourism-website#21]
**When I'm hovering it's transforming and covering the content as shown below.**

![Screenshot (203)](https://user-images.githubusercontent.com/90236635/184640945-d2674400-c431-4c30-b757-424e47e4a7f4.png)

### Suggestive changes : 

Either change the transform scale or move the content little left.

**Comment by hurricanejay** [comment]
Hi @PritamSarbajna - I'd like to tackle this if you don't mind.

**Comment by PritamSarbajna** [comment]
Hey @hurricanejay sure go for it. should I assign you ?

**Comment by hurricanejay** [comment]
@PritamSarbajna  yes please assign me! thanks.

**Comment by Brainiac-M** [comment]
I'm interested in working on this issue

**Comment by prakhartiwari2507** [comment]
Hey, I can help with this one too. Can you assign me this?

**Comment by PritamSarbajna** [comment]
Hey @prakhartiwari2507 and @Brainiac-M you both can collaborate with @hurricanejay for this issue and try to resolve it

**Comment by hurricanejay** [comment]
Hey @prakhartiwari2507 and @Brainiac-M, I just did a PR for this https://github.com/PritamSarbajna/tourism-website/compare/main...hurricanejay:jay_bugfix?expand=1 

![Screen Shot 2022-08-15 at 2 51 45 PM](https://user-images.githubusercontent.com/55364133/184697508-c48e2749-b427-4765-9326-be2493cb0d8a.png)

I did notice that on large screens the images look like this with the image attached around 1688px. I assume he still wants it to stack as 2x2 @PritamSarbajna  do you want them to address this?

**Comment by prakhartiwari2507** [comment]
Hey @hurricanejay, I don't know if @PritamSarbajna wanted to change the layout of the images. I have made the required changes without changing the layout. Let him tell is that what he wanted or not.

**Comment by PritamSarbajna** [comment]
> Hey @prakhartiwari2507 and @Brainiac-M, I just did a PR for this https://github.com/PritamSarbajna/tourism-website/compare/main...hurricanejay:jay_bugfix?expand=1
> 
> ![Screen Shot 2022-08-15 at 2 51 45 PM](https://user-images.githubusercontent.com/55364133/184697508-c48e2749-b427-4765-9326-be2493cb0d8a.png)
> 
> I did notice that on large screens the images look like this with the image attached around 1688px. I assume he still wants it to stack as 2x2 @PritamSarbajna do you want them to address this?
> 
> P.S. - this is my first open source contribution. LMK if I'm following the correct steps. Thanks!

**Hey @hurricanejay you haven't made a PR have you ? also I don't wanted to change the layout welcome to opensource  contribution both of you you can find various beginner friendly issue in this repo feel free to resolve them.**

**Comment by PritamSarbajna** [comment]
Hey @prakhartiwari2507 this was assigned to @hurricanejay actually I'm approving your PR but don't do this frequently. Thank you 🙌

**Comment by prakhartiwari2507** [comment]
Oh, @PritamSarbajna and @hurricanejay  I am sorry, you already I am not much experienced, this is my starting. I thought if I could solve the issue then there was no problem. I will take care of this in the future, and talk with the assignee to collaboratively solve the issue.
