### ISSUE TITLE
[BUG] : Button's behavior is not correct 

### ISSUE THREAD

**Issue by PritamSarbajna** [PritamSarbajna/tourism-website#25]
When I'm hovering in the button it's texts are also changing to same color as background thus I can't see what is written also when I specifically hover over the texts they are much more readable. Fix this.

https://user-images.githubusercontent.com/90236635/184767680-e943922d-3ced-422f-ab6e-ff0af5a8487b.mp4

**Comment by Akidane47** [comment]
I'd like to be assigned to this if it's still open source

**Comment by prakhartiwari2507** [comment]
I can solve it!

**Comment by PritamSarbajna** [comment]
Hey sure @Akidane47 and @prakhartiwari2507 make a PR
