### ISSUE TITLE
[DOCS] : Make a CONTRIBUTING.md

### ISSUE THREAD

**Issue by PritamSarbajna** [PritamSarbajna/tourism-website#31]
Hey everyone because there are a lot of contributors here and sometimes they are new to opensource I think it'd be great if a CONTRIBUTING.md is here

**Comment by Techkrish1** [comment]
Can you assign me to create Contributing.md?

**Comment by Techkrish1** [comment]
Are you assigned me? I am very excited about it. Please assign me.

**Comment by PritamSarbajna** [comment]
Yeah @Techkrish1 you can see in before your message 

![Screenshot (209)](https://user-images.githubusercontent.com/90236635/185436623-1e47cb22-3ad6-4374-8a6c-3bcb19b78e3c.png)

> Please ask any help regarding this issue here -> #36

**Comment by PritamSarbajna** [comment]
Thanks @Techkrish1

**Comment by Techkrish1** [comment]
You are welcome.
