### ISSUE TITLE
[DOCS] : Make a Code_of_Conduct.md

### ISSUE THREAD

**Issue by lubnafathima** [PritamSarbajna/tourism-website#37]
Hey, @PritamSarbajna thanks for this fantastic beginner-friendly project.
I'm sure this will help people starting out in Open source like me
I just had a suggestion that for an Open Source project it would be helpful to have a **code of conduct** file.
> Kindle refers to this: 
> https://opensource.guide/code-of-conduct/

Also if it's okay with you, could you assign me to it?

**Comment by PritamSarbajna** [comment]
Yeah sure @lubnafathima I was also thinking about this glad you raised this issue please go for it 🙌

**Comment by lubnafathima** [comment]
please check the pull request #39!

**Comment by PritamSarbajna** [comment]
Thanks @lubnafathima ✨
