### ISSUE TITLE
[IMPROVEMENT] : update navbar

### ISSUE THREAD

**Issue by PritamSarbajna** [PritamSarbajna/tourism-website#4]
Make the navbar transparent or give it a glass effect. Like this website's [navbar](https://demo-coffee-website.netlify.app/)

**Comment by hassana123** [comment]
Would like to work on the navbar @PritamSarbajna

**Comment by PritamSarbajna** [comment]
Yeah @hassana123 go for it !

**Comment by hassana123** [comment]
done  #14

**Comment by PritamSarbajna** [comment]
Thank you @hassana123 🙌
make sure to check other [issues](https://github.com/PritamSarbajna/tourism-website/issues)
