### ISSUE TITLE
[IMPROVEMENT] : Change the logo

### ISSUE THREAD

**Issue by PritamSarbajna** [PritamSarbajna/tourism-website#40]
Please change the logo you can see below :

![Screenshot (210)](https://user-images.githubusercontent.com/90236635/185650613-43cc13a8-90ad-4e6f-8b75-a45dd109d548.png)

#### Here is what you can do:

- Change the font of the logo
- Replace it with a adventure logo (png file)

> NOTE : You have to do either of them don't implement both
>
> If you're thinking to change the logo with a png file then before making PR do show me here

**Comment by Brainiac-M** [comment]
Can I work on this?

**Comment by PritamSarbajna** [comment]
Yeah sure @Brainiac-M 
**go for it** 🙌

**Comment by Brainiac-M** [comment]
Done.  Check out #47 
![image](https://user-images.githubusercontent.com/49205684/185973834-bd07cd92-737f-43b7-8b90-7eb90f5c845f.png)

**Comment by Brainiac-M** [comment]
I have updated the logo. Check out #47 

![image](https://user-images.githubusercontent.com/49205684/185996136-66ab4db9-550e-4c09-bd98-207c09cd0361.png)
