### ISSUE TITLE
[IMPROVEMENT] : Make UI responsive

### ISSUE THREAD

**Issue by AmitBarman99** [PritamSarbajna/tourism-website#53]
1> The home background image is very big size, plz compressed it.
2> In Explore section the glass effects box UI is leftside aligned. (when screen >850px)
3> The things in this explore box are also not responsive.
4> About us section should have a leftside paddings at screen >770px.
5> Contribution box are too big.
6> There is no contribution part in navbar.
7> Navbar has a few less padding.

![Screenshot (29)](https://user-images.githubusercontent.com/107401504/187073970-4a22142f-ff8a-456e-a70a-287f3e8d577b.png)
![Screenshot (30)](https://user-images.githubusercontent.com/107401504/187073983-afab8814-1e0e-40e2-8c9c-e26d06470e1a.png)

**Comment by AmitBarman99** [comment]
Hey @PritamSarbajna 
I have solved all the problems related to this website.
Here you can see 

[Click here](https://amitbarman99.github.io/Tourism-website/)

**Comment by PritamSarbajna** [comment]
@AmitBarman99 this is so awesome man please make a PR 🙌

> I also added you as a collaborator

**Comment by AmitBarman99** [comment]
I made a PR #54 

 fixes #53

**Comment by AmitBarman99** [comment]
I made a PR #54
