### ISSUE TITLE
[IMPROVEMENT] : FIX the media query on the font-size in the box inside the contact section on smaller screens it overflows!

### ISSUE THREAD

**Issue by abitsalihu** [PritamSarbajna/tourism-website#56]
The text inside the box overflows when in smaller screens, also the content - (paragraph and icon) is not aligned in the center in the Y(axis).
<img width="1180" alt="Screen Shot 2022-09-03 at 20 35 34" src="https://user-images.githubusercontent.com/94648837/188283946-a53e502f-33db-4bb7-9c0e-f150abb5a028.png">

**Comment by abitsalihu** [comment]
I would love to work on this if it could be assigned to me :)

**Comment by PritamSarbajna** [comment]
Yeah sure @abitsalihu go for it 🙌

**Comment by abitsalihu** [comment]
I will also add improve the hover effect is has, so I don't make another [improve] issue.

**Comment by PritamSarbajna** [comment]
Yeah sure
