### ISSUE TITLE
[FEATURE] : Light/Dark theme toggle 

### ISSUE THREAD

**Issue by anchalsinghrajput** [PritamSarbajna/tourism-website#58]
You can add a theme toggle button in your website, which will change your website to go from dark mode to light and vice versa.
Have a look on below one.
 (https://codepen.io/PaulinaSurazynska/pen/bGVpBOb)

**Comment by PritamSarbajna** [comment]
@anchalsinghrajput that'd be great but for that we really need to discuss about your color proposal for the website.

**Comment by Abhishekcuso** [comment]
Hey, I am Abhishek Khairnar . How can I contribute to this open source project for my open source class? Please assign me a task.
Contact Me: [khairnarabma19ie@student.mes.ac.in](mailto:khairnarabma19ie@student.mes.ac.in)
GitHub: Abhishekcuso

**Comment by PritamSarbajna** [comment]
Hey @Abhishekcuso there is a few issues in the issues section if you think you can work on it or fix it I'd be love to assign you on that. Also, you can see the website and if you can in anyhow you can improve the website, you can mention and I'll assign you.

**Comment by Abhishekcuso** [comment]
yes sure I'd love to work on this

**Comment by Abhishekcuso** [comment]
here is **html** code for the above 
<div>
	<input type="checkbox" class="checkbox" id="chk" />
	<label class="label" for="chk">
		<i class="fas fa-moon"></i>
		<i class="fas fa-sun"></i>
		<div class="ball"></div>
	</label>
</div>




---------------------------------------------------------------------------------------
**CSS Code**

@import url('https://fonts.googleapis.com/css?family=Muli&display=swap');

* {
	box-sizing: border-box;
}

body {
	background-color: #fafafa;
	display: flex;
	align-items: center;
	justify-content: center;
	height: 100vh;
	margin: 0;
	transition: background 0.2s linear;
}

body.dark {
	background: #292C35;
}

.checkbox {
	opacity: 0;
	position: absolute;
}

.label {
	background-color: #111;
	border-radius: 50px;
	cursor: pointer;
	display: flex;
	align-items: center;
	justify-content: space-between;
	padding: 5px;
	position: relative;
	height: 26px;
	width: 50px;
	transform: scale(1.5);
}

.label .ball {
	background-color: #fff;
	border-radius: 50%;
	position: absolute;
	top: 2px;
	left: 2px;
	height: 22px;
	width: 22px;
	transform: translateX(0px);
	transition: transform 0.2s linear;
}

.checkbox:checked + .label .ball {
	transform: translateX(24px);
}


.fa-moon {
	color: #f1c40f;
}

.fa-sun {
	color: #f39c12;
}
----------------------------------------------------------------------------------------------------------------
**Java Script**
const chk = document.getElementById('chk');

chk.addEventListener('change', () => {
	document.body.classList.toggle('dark');
});

**Comment by Abhishekcuso** [comment]
**html Code** 

 <div>
	 <input type="checkbox" class="checkbox" id="chk" />
	 <label class="label" for="chk">
		 <i class="fas fa-moon"></i>
		 <i class="fas fa-sun"></i>
		 <div class="ball"></div>
	 </label>
 </div>

**Comment by PritamSarbajna** [comment]
Hey @Abhishekcuso this isn't making any until you make a PR sorry also this issue isn't assigned to you :")

**Comment by Abhishekcuso** [comment]
since you are working on react , its hard for me to run this on npm. So id suggest you to try out the above code .
also may I know about the thing you talked about color preference

**Comment by PritamSarbajna** [comment]
> since you are working on react , its hard for me to run this on npm. So id suggest you to try out the above code . also may I know about the thing you talked about color preference

Hi @Abhishekcuso This project doesn't contain react. It's a pure html, css, javascript website

**Comment by Abhishekcuso** [comment]
sorry for that, so wont you be able to assign this task to me?

**Comment by PritamSarbajna** [comment]
> sorry for that, so wont you be able to assign this task to me?

Yeah I can assign but I have already assigned you on two issues please do finish them first and let me know. I'd love to assign you on this 🙌

**Comment by Abhishekcuso** [comment]
sorry but I am unable to view where you've assigned me , may I please know

**Comment by PritamSarbajna** [comment]
Yeah on the issues you want to work on also you have replied thank you there

**Comment by Abhishekcuso** [comment]
oh that's someone else and not me  , it's sayali while I'm Abhishek . You've assigned the task to her

**Comment by Abhishekcuso** [comment]
No problem I'll check for another open source git repository issues thanks alot :)

**Comment by PritamSarbajna** [comment]
> oh that's someone else and not me , it's sayali while I'm Abhishek . You've assigned the task to her

Okay that's a mistake I got there apologies

**Comment by PritamSarbajna** [comment]
yeah sure @Iamslok here you go

**Comment by suraj1609** [comment]
heyy, i am suraj kanse,i would like to contribute to this issue.can you assign me this work if you dont mind.

**Comment by PritamSarbajna** [comment]
Hey @suraj1609 sorry this issue is already assigned to @Iamslok. Make sure to check other issues 🙌

**Comment by Iamslok** [comment]
<img width="685" alt="image" src="https://user-images.githubusercontent.com/90669886/192084535-ad575bd5-adc5-4840-b5ec-17738ef8efb0.png">
@PritamSarbajna when I am trying to push the code it's showing like the above image, can you please help me with that

**Comment by PritamSarbajna** [comment]
Do this if it helps ```git pull origin Light/dark_Toggle```
then ```git push```

**Comment by Iamslok** [comment]
<img width="635" alt="image" src="https://user-images.githubusercontent.com/90669886/192084817-3228b550-c976-4973-baf3-99d8d0860858.png">
@PritamSarbajna Denied request

**Comment by PritamSarbajna** [comment]
Try it : ```git push origin HEAD```

**Comment by Iamslok** [comment]
<img width="493" alt="image" src="https://user-images.githubusercontent.com/90669886/192085315-4ba8b4ab-1b20-45e1-9769-61dd808386ff.png">
It's done right, how can I create a pull request?

**Comment by PritamSarbajna** [comment]
Just go to you forked repo you can now see a option to make a pull request

**Comment by Iamslok** [comment]
Yeah @PritamSarbajna it's done, thank you

**Comment by Abhishekcuso** [comment]
np
