### ISSUE TITLE
[FEATURE] : Make the navbar buttons easily clickable 

### ISSUE THREAD

**Issue by prakhartiwari0** [PritamSarbajna/tourism-website#59]
**Is your feature request related to a problem? Please describe.**
When we hover over navbar buttons, they change colour, and this makes the user think they are now clickable and they will click, but actually, they are only clickable directly on the text, which is a little bit confusing and can spoil the experience

**Describe the solution you'd like**
We can give the border to the links and padding to them, which will make the whole blank area clickable, and then give the hover effect to them, or if the property and class already exist we can simply provide the links with that class.

**Recording of the issue**

https://user-images.githubusercontent.com/65062036/189111299-ef51718a-9e8b-44d6-a43d-100e20293368.mp4

**Comment by PritamSarbajna** [comment]
Hey @prakhartiwari0 great observation !! please fix the issue.
