### ISSUE TITLE
[FEATURE] : Update the logo of the website

### ISSUE THREAD

**Issue by PritamSarbajna** [PritamSarbajna/tourism-website#62]
Hey **contributors**, 
I think the logo of the website needs to be changed. do mention if you want to work on this, then I'll assign

**Comment by sayalihere** [comment]
@PritamSarbajna  hey , we would like to take up this issue and create a project
Contributors: Sayali Ghanwat , Nilesh Jha , Ritik Jain , Sidhharth Kanojia .

**Comment by PritamSarbajna** [comment]
@sayalihere Go for it ✨

**Comment by akuliakuli** [comment]
Hello,looks like the issue is still open,can you please assign me to it ?
i would be very grateful

**Comment by PritamSarbajna** [comment]
Hey @akuliakuli thanks for being interested in this repo but unfortunately this issue is been assigned to @sayalihere.
Feel free to check other issues or if you want to collaborate just contact with the assignees 🙌

**Comment by khoseomkar** [comment]
Hey i love making Logo for website. I would love to work on this issue and can provide a great logo for website
