### ISSUE TITLE
[BUG] : Between the lists in the navbar the gap should be less

### ISSUE THREAD

**Issue by PritamSarbajna** [PritamSarbajna/tourism-website#63]
See the navbar, the lists are covering the whole navbar. I think if the gap between them anyhow reduces it'd be better.

**Comment by PritamSarbajna** [comment]
Hey @sayalihere you have commented on three issues that you guys want to work on. Do you want to work on all these three issues ??

**Comment by PritamSarbajna** [comment]
Because @abitsalihu commented here first I'm assigning him but @sayalihere do check the other issues 🙌

**Comment by abitsalihu** [comment]
@PritamSarbajna  thank you, I will do the PR tomorrow at the latest . 🙂

**Comment by PritamSarbajna** [comment]
@abitsalihu Yeah sure take your time, there ain't no deadline :")

**Comment by sayalihere** [comment]
@PritamSarbajna  hey, so can you assign the issue of dummy text and logo ??

**Comment by PritamSarbajna** [comment]
> @PritamSarbajna hey, so can you assign the issue of dummy text and logo ??

Yeah sure I'm assigning you there !!

**Comment by sayalihere** [comment]
@PritamSarbajna thankyou !

**Comment by PritamSarbajna** [comment]
Thanks @abitsalihu ✨

**Comment by abitsalihu** [comment]
Thank you  as well! @PritamSarbajna
