### ISSUE TITLE
[FEATURE] : Change dummy texts to original texts

### ISSUE THREAD

**Issue by PritamSarbajna** [PritamSarbajna/tourism-website#64]
In the website there is a lot of dummy texts (_lorem ipsum texts_). The website should contain original texts like a real tourism website. Please update the texts with relevant original texts.

**Comment by sayalihere** [comment]
@PritamSarbajna we would like to take up this issue and create a project
Contributors: Sayali Ghanwat, Nilesh Jha, Ritik Jain, Siddhart kanojia

**Comment by PritamSarbajna** [comment]
Hey @sayalihere here you go !
you can also collaborate with others to contribute to this issue 🙌

**Comment by sayalihere** [comment]
@PritamSarbajna thankyou so much !

**Comment by PritamSarbajna** [comment]
@sayalihere my pleasure ✨

**Comment by Abhishekcuso** [comment]
may I work on with this issue?

**Comment by sayalihere** [comment]
Hey @PritamSarbajna  can I do the 2 issues which are assigned to me after few days as I m indulged in some other work ? Is it okay with you ?

**Comment by PritamSarbajna** [comment]
Yeah sure mate @sayalihere

**Comment by suraj1609** [comment]
hey  i am suraj kanse, can i handle this issue as soon as possible can u plzz assign me for work on it.

**Comment by PritamSarbajna** [comment]
Hey @suraj1609 make sure to comment to other issues in this repo where the issue is not tagged as **work in progress**

**Comment by sayalihere** [comment]
@PritamSarbajna  hello , as i am new to this contributing society can you tell me about the option i got that is CLOSE PULL REQUEST . Do i have to click on that or not ?

**Comment by PritamSarbajna** [comment]
@sayalihere don't click on that. If you click on that the PR will close without merging
