### ISSUE TITLE
[FEATURE] : Add A Favicon

### ISSUE THREAD

**Issue by NageshMandal** [PritamSarbajna/tourism-website#67]
![19 09 2022_15 55 21_REC](https://user-images.githubusercontent.com/106006006/190998637-208e58bd-014a-4804-a87b-2a19df71a3a2.png)

**Comment by NageshMandal** [comment]
I want to work on this issue. Could you please assign it to me.

**Comment by PritamSarbajna** [comment]
Yeah sure @NageshMandal please go for it

**Comment by PritamSarbajna** [comment]
Thank you @NageshMandal 🙌
