### ISSUE TITLE
[IMPROVEMENT] : Change the font

### ISSUE THREAD

**Issue by PritamSarbajna** [PritamSarbajna/tourism-website#7]
Change the font of the whole website

**Comment by SifonSolomon** [comment]
Hi, I would like to work on this project.

**Comment by PritamSarbajna** [comment]
yeah sure @SifonSolomon go for it

**Comment by SifonSolomon** [comment]
ok

**Comment by SifonSolomon** [comment]
done

**Comment by Andyy-18** [comment]
Hey @PritamSarbajna , I want to work on this project. Can I ?

**Comment by PritamSarbajna** [comment]
yeah sure @Andyy-18 why not go for it

**Comment by Olamide0411** [comment]
Hi, I would like to work on this project.

**Comment by PritamSarbajna** [comment]
Hey @Olamide0411 check the issues if you can resolve any
