### ISSUE TITLE
[IMPROVEMENT] : Card length issue

### ISSUE THREAD

**Issue by Iamslok** [PritamSarbajna/tourism-website#73]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/90669886/192085943-d2dfb608-8a2d-47d3-bf66-0c085a2398ad.png">

**Comment by Iamslok** [comment]
@PritamSarbajna We can give fixed length to those cards and we can overflow those the description below the image text

**Comment by PritamSarbajna** [comment]
@Iamslok go for it ✨

**Comment by Iamslok** [comment]
@PritamSarbajna the card images are having different heights and widths, we need to change the images

**Comment by Iamslok** [comment]
@PritamSarbajna when we tested it in local it's looking fine,  but then when we push it to live the card has some size issues

**Comment by PritamSarbajna** [comment]
@Iamslok Your closed PR was looking fine the cards were same size
