### ISSUE TITLE
[BUG] : Menu button not working as expected, fix navbar

### ISSUE THREAD

**Issue by PritamSarbajna** [PritamSarbajna/tourism-website#75]
The navbar was like this 

![Screenshot (223)](https://user-images.githubusercontent.com/90236635/193247373-14c84111-ce8f-45d3-9379-fb36ce365600.png)

It is now like this :

![Screenshot (222)](https://user-images.githubusercontent.com/90236635/193247431-1d0c27d3-3180-4e15-84e6-3f369675fa0a.png)

**Ignore the designs and fix the navbar to be compatible.**

**Comment by Iamslok** [comment]
@PritamSarbajna can you assign me

**Comment by PritamSarbajna** [comment]
Yeah sure @Iamslok go for it 🙌

**Comment by Siddhoo** [comment]
@PritamSarbajna hey , we would like to take up this issue and create a project for our College lab.
Contributors: Ritik Jain, Siddhart kanojia.
please assign me this issue @kanojiyasisu19it@student.mes.ac.in

**Comment by ritikj07** [comment]
hey , we would like to take up this issue and create a project for our College lab.

please assign me this issue [@jainrr19@student.mes.ac.in]

**Comment by Iamslok** [comment]
![image](https://user-images.githubusercontent.com/90669886/196038879-c2cfda0b-c13c-402c-b3b3-a773a65a0a21.png)
@PritamSarbajna Is this looking good
