### ISSUE TITLE
[BUG] : After page load or reload, a border appears around nav elements upon hovering

### ISSUE THREAD

**Issue by abinjohn123** [PritamSarbajna/tourism-website#76]
## Description

If the mouse hovers over the nav elements after the webpage is loaded or reloaded, a white border appears around the hovered element. This behavior stops after one of the nav elements is clicked.

![NVIDIA_Share_oXeuLdZRI1](https://user-images.githubusercontent.com/15942221/195624330-8680270d-a8f1-44c4-b319-0eed0592e970.gif)

## Expected Behavior

A border should only appear on a nav element after it is clicked.

**Comment by prakhartiwari0** [comment]
@abinjohn123 This is not happening in my side

**Comment by abinjohn123** [comment]
> @abinjohn123 This is not happening in my side

I'm testing the[ link attached in the repo](https://simple-tourism-organization.netlify.app/)
I tried both Chrome(Version 106.0.5249.119 (Official Build) (64-bit)) and Firefox (105.0.3 (64-bit))

**Comment by prakhartiwari0** [comment]
> > @abinjohn123 This is not happening in my side
> 
> I'm testing the[ link attached in the repo](https://simple-tourism-organization.netlify.app/) I tried both Chrome(Version 106.0.5249.119 (Official Build) (64-bit)) and Firefox (105.0.3 (64-bit))

I am only testing on brave browser, but its working perfectly for me, no problem.

**Comment by PritamSarbajna** [comment]
Hi @abinjohn123 yeah you can fix it. @prakhartiwari0 I'm using firefox and this is a bug clearly.

**Comment by abinjohn123** [comment]
Thank you 👍🏽
