### ISSUE TITLE
[BUG] : 

### ISSUE THREAD

**Issue by constneophyte** [PritamSarbajna/tourism-website#81]
**Describe the bug**
When the website is in light mode the headers on the homepage are not clearly seen.

![issue 1](https://user-images.githubusercontent.com/99181713/210342866-801a4674-d30b-47db-b4df-5f846977ce3f.PNG)
 here.

**Comment by PritamSarbajna** [comment]
Sure go ahead @constneophyte 🚀

**Comment by constneophyte** [comment]
It was never a bug at first, its an error on my end.

**Comment by PritamSarbajna** [comment]
@constneophyte got it make sure to check other issues.
