### ISSUE TITLE
[BUG] : Home page logo is not aligned

### ISSUE THREAD

**Issue by aulth** [PritamSarbajna/tourism-website#95]
**Describe the bug**
I have identified a bug in the "tourism-website" repository related to the positioning of the logo image on the home page. Currently, the "Adventure" logo is not correctly aligned with the vertical center of the header.

**Screenshots**
![Bug Screenshot](https://i.ibb.co/WKFvQ91/Screenshot-2023-05-27-213703.jpg)

**Comment by PritamSarbajna** [comment]
Thank you @aulth  ❤
