### ISSUE TITLE
[BUG] : "Learn More" Button Not Responsive

### ISSUE THREAD

**Issue by amolgorithm** [PritamSarbajna/tourism-website#97]
**Describe the bug**
Typically, the "Learn More" button is supposed to go to an info page or pop-up. However, this button does not seem to be responsive, as it does not really do anything in terms of the client-side domain. Unless this is what it is supposed to be doing, I was thinking an info page, pop-up, or even scrolling down to an info section, could be added. Maybe, a section below could be about the Learn More info, and on click of the button, the page could scroll down to that section. That may be aesthetically nice as it would follow your website's GUI and schema.

**Screenshots**
![issue](https://github.com/PritamSarbajna/tourism-website/assets/123842348/6351b4de-3728-4145-bfa3-20af235b35c6)

**Additional context**
On the click of the button, some sort of form response seems to be occurring, as the link goes from [](https://simple-tourism-organization.netlify.app) to [](https://simple-tourism-organization.netlify.app/#), but the button does not fulfill the purpose of a "Learn More" button. By the way, very nice GUI.

**Comment by PritamSarbajna** [comment]
@amolgorithm Yeah the `learn more` button doesn't work. I don't want the website to have a new section because you can see the navbar is already full instead we can route this to a section as you're saying. So I'm thinking we can make the about section to be more cool. Let me know is it a better idea or not. If so then how you're gonna make this section more cool.

**Comment by amolgorithm** [comment]
@PritamSarbajna True, I consider that to be a better idea.  So, to make the about section better, we could add a mission statement or a deeper purpose initiative of the website. Then, at the end, we could add a short but catchy slogan for the website. From a perspective of GUI, I feel that it pretty much looks very good, however, one thing that seems like a good thing to add is a bigger version of the  logo in the right side of the about section. I was thinking, on scroll to that section, there could be a transition put on the logo image element such that it fades in or does another type of animation. Please let me know if all the above are ok and can be implemented. Thank you.

**Comment by PritamSarbajna** [comment]
@amolgorithm I think your idea is good but can you show me some draft of the idea anyhow if possible ?

**Comment by amolgorithm** [comment]
@PritamSarbajna Sure, here is the forked repo where I added the changes: [https://github.com/amolgorithm/tourism-website](https://github.com/amolgorithm/tourism-website).
The changes included all of the ideas I had proposed and successfully works. Sorry, I did not add a preview, you would need to clone it to see it.

**Comment by PritamSarbajna** [comment]
@amolgorithm Can you just make a test PR, so that I won't have to clone and setup locally.

**Comment by amolgorithm** [comment]
@PritamSarbajna Sure, that has been done.

**Comment by PritamSarbajna** [comment]
Hey @amolgorithm, Thanks for thinking that way but it'd be nice if you remove the paragraph and place carousel there which is interactive.

**Comment by amolgorithm** [comment]
Hi @PritamSarbajna, By carousel, I believe you mean like a div where you can _slide_ through images using left and right arrows. Is that right? If it is, then should the carousel's height fill the height of the about section? Also, is it okay if I use Bootstrap?
Btw, the issue says that no one is assigned, but I am assigned to this, right?

**Comment by PritamSarbajna** [comment]
@amolgorithm This a frontend focused website so I don't recommend you to use bootstrap but you can copy paste any html code and css classes as long as it is pure HTML and vanilla CSS.
> PS: I forgot to assign you but here you go 🚀

**Comment by amolgorithm** [comment]
Hey @PritamSarbajna, I had finished the carousel, but I just realized a big problem that applies to your repo as well. The icon/logo for the website is from a drive local content link, which is currently down. It does not work, which is why, if you clicked on your link and went to the site, the image would be unavailable.

**Comment by amolgorithm** [comment]
@PritamSarbajna Yep, that has been done. Check the same Test PR to see the new updated version.
For the carousel, click on the faded image if you want to spotlight it in the center to view it.

I have add a new mountain logo as well.

**Comment by PritamSarbajna** [comment]
@amolgorithm Damn !! this is so nice ✨

If everything you need to do is finished I can merge it.

**Comment by amolgorithm** [comment]
Hello @PritamSarbajna, I have pretty much fixed the mobile responsiveness of the carousel, so you can take a look again. For a small width screen, I remove the logo in the about page, because there occurs a flexbox issue that completely complicates the whole project. So, the carousel is mobile responsive now though. I am done with everything I need to do on my side, so if you are good with it, you can merge it and the issue could be closed.

**Comment by PritamSarbajna** [comment]
@amolgorithm Thank you. Merged your PR ✨
